/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LinesRouteImport } from './routes/lines'
import { Route as EntriesRouteImport } from './routes/entries'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LineLineIdRouteImport } from './routes/line.$lineId'
import { Route as EntryNewRouteImport } from './routes/entry.new'
import { Route as EntryEntryIdRouteImport } from './routes/entry.$entryId'

const LinesRoute = LinesRouteImport.update({
  id: '/lines',
  path: '/lines',
  getParentRoute: () => rootRouteImport,
} as any)
const EntriesRoute = EntriesRouteImport.update({
  id: '/entries',
  path: '/entries',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LineLineIdRoute = LineLineIdRouteImport.update({
  id: '/line/$lineId',
  path: '/line/$lineId',
  getParentRoute: () => rootRouteImport,
} as any)
const EntryNewRoute = EntryNewRouteImport.update({
  id: '/entry/new',
  path: '/entry/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EntryEntryIdRoute = EntryEntryIdRouteImport.update({
  id: '/entry/$entryId',
  path: '/entry/$entryId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/entries': typeof EntriesRoute
  '/lines': typeof LinesRoute
  '/entry/$entryId': typeof EntryEntryIdRoute
  '/entry/new': typeof EntryNewRoute
  '/line/$lineId': typeof LineLineIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/entries': typeof EntriesRoute
  '/lines': typeof LinesRoute
  '/entry/$entryId': typeof EntryEntryIdRoute
  '/entry/new': typeof EntryNewRoute
  '/line/$lineId': typeof LineLineIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/entries': typeof EntriesRoute
  '/lines': typeof LinesRoute
  '/entry/$entryId': typeof EntryEntryIdRoute
  '/entry/new': typeof EntryNewRoute
  '/line/$lineId': typeof LineLineIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/entries'
    | '/lines'
    | '/entry/$entryId'
    | '/entry/new'
    | '/line/$lineId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/entries'
    | '/lines'
    | '/entry/$entryId'
    | '/entry/new'
    | '/line/$lineId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/entries'
    | '/lines'
    | '/entry/$entryId'
    | '/entry/new'
    | '/line/$lineId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  EntriesRoute: typeof EntriesRoute
  LinesRoute: typeof LinesRoute
  EntryEntryIdRoute: typeof EntryEntryIdRoute
  EntryNewRoute: typeof EntryNewRoute
  LineLineIdRoute: typeof LineLineIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lines': {
      id: '/lines'
      path: '/lines'
      fullPath: '/lines'
      preLoaderRoute: typeof LinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entries': {
      id: '/entries'
      path: '/entries'
      fullPath: '/entries'
      preLoaderRoute: typeof EntriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/line/$lineId': {
      id: '/line/$lineId'
      path: '/line/$lineId'
      fullPath: '/line/$lineId'
      preLoaderRoute: typeof LineLineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry/new': {
      id: '/entry/new'
      path: '/entry/new'
      fullPath: '/entry/new'
      preLoaderRoute: typeof EntryNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry/$entryId': {
      id: '/entry/$entryId'
      path: '/entry/$entryId'
      fullPath: '/entry/$entryId'
      preLoaderRoute: typeof EntryEntryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  EntriesRoute: EntriesRoute,
  LinesRoute: LinesRoute,
  EntryEntryIdRoute: EntryEntryIdRoute,
  EntryNewRoute: EntryNewRoute,
  LineLineIdRoute: LineLineIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
